##############################
# !REQUIRES MANUAL ADOPTION! #
##############################

# Set working directory to location of the R code
# Should be the same as in simulations.R
setwd("~/replication-kit-tse-2018-costmodel/R-Code/")

# Define path where the plots shall be stored
# Folder must exist, otherwise the plot generation will fail
plots.path = "cost-plots/"

# Load correct results file for plotting
# Option 1. The results we provided as part of the replication package (default)
load(file="provided-results.RData")
# Option 2. Results that were generated by executing the simulations.R script of the replication package
# load(file="simulation-results.RData")


#######################
# SETUP R Environment #
#######################
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)

source("functions.R")

####################################
# Code for generating result plots #
####################################

# Define if the actual values are shown as scatterplot or if only trend lines should be shown
plots.scatterplot = TRUE
# Define if the legend is added to the plots
plots.legend = FALSE
# Define if the title is added to the plots
plots.title = FALSE

# Generate all plots
for( iter.defects in 1:length(parameters.numDefects) ) {
  for( iter.pqf in 1:length(parameters.pqf) ) {
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(accuracy, constNM.lower),
                aes_upper=aes(accuracy, constNM.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="accuracy",
                costmodel="constnm",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(recall, constNM.lower),
                aes_upper=aes(recall, constNM.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="recall",
                costmodel="constnm",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(precision, constNM.lower),
                aes_upper=aes(precision, constNM.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="precision",
                costmodel="constnm",
                path=plots.path)
    
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(accuracy, const1M.lower),
                aes_upper=aes(accuracy, const1M.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="accuracy",
                costmodel="const1m",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(recall, const1M.lower),
                aes_upper=aes(recall, const1M.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="recall",
                costmodel="const1m",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(precision, const1M.lower),
                aes_upper=aes(precision, const1M.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="precision",
                costmodel="const1m",
                path=plots.path)
    
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(accuracy, const11.lower),
                aes_upper=aes(accuracy, const11.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="accuracy",
                costmodel="const11",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(recall, const11.lower),
                aes_upper=aes(recall, const11.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="recall",
                costmodel="const11",
                path=plots.path)
    plotResults(results=results, 
                ndefects=parameters.numDefects[iter.defects],
                pqf=parameters.pqf[iter.pqf],
                aes_lower=aes(precision, const11.lower),
                aes_upper=aes(precision, const11.upper),
                withScatterplot=plots.scatterplot,
                withLegend=plots.legend,
                withTitle=plots.title,
                metric="precision",
                costmodel="const11",
                path=plots.path)
  }
}